version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: rurl-mysql
    environment:
      MYSQL_DATABASE: rurl
      MYSQL_ROOT_PASSWORD: Ux-661525
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
